const ANALYTICS_EVENTS = {
  VISIT_EST: "VISIT_EST",
  VIEW_CARTA: "VIEW_CARTA",
  VIEW_PRODUCT: "VIEW_PRODUCT",
  WHATSAPP_PRODUCT_ORDER: "WHATSAPP_PRODUCT_ORDER",
};

module.exports = ANALYTICS_EVENTS;
